### ISSUE TITLE
A trivial question: How to specify the k8s api url in this setting

### ISSUE THREAD

**Issue by kuanghaochina** [samsung-cnct/k2-logging-fluentd-daemonset#2]

**Comment by coffeepac** [comment]
@kuanghaochina not sure what you're referring to.  can please provide some context?

**Comment by kuanghaochina** [comment]
@coffeepac I thought it supports environment variables of setting those kubernetes variables in plugin fluent-plugin-kubernetes_metadata_filter. The problem has been solved. Thanks. :)

**Comment by coffeepac** [comment]
@kuanghaochina okay!  also, we have a helm chart for this:  https://github.com/samsung-cnct/k2-charts/tree/master/central-fluentd  its part of our central logging chart if you're interested.

If you have more comments or questions feel free to ask them.  I'm going to close this for now.
