### ISSUE TITLE
Docker image build fails 

### ISSUE THREAD

**Issue by mbachtel** [samsung-cnct/k2-logging-fluentd-daemonset#6]
Building a docker image using command `docker build -t k2-logging-fluentd-daemonset .`
fails with the following output:

    sudo: unknown user: fluent
    sudo: unable to initialize policy plugin
    The command '/bin/sh -c apk --no-cache --update add sudo build-base ruby-dev &&     sudo -u fluent gem install fluent-plugin-secure-forward &&     sudo -u fluent gem install fluent-plugin-kafka &&    sudo -u fluent gem install fluent-plugin-record-reformer &&     sudo -u fluent gem install zookeeper &&     sudo -u fluent gem install fluent-plugin-kubernetes_metadata_filter &&     sudo apk add procps &&     rm -rf /home/fluent/.gem/ruby/2.3.0/cache/*.gem && sudo -u fluent gem sources -c &&     apk del sudo build-base ruby-dev && rm -rf /var/cache/apk/*' returned a non-zero code: 1

**Comment by leahnp** [comment]
We should probably not pull "latest" fluentd base image in the Dockerfile when we address this issue.

**Comment by mbachtel** [comment]
I was able to validate the deployment
brought up the specified number of instances
and see the logging behavior

waiting to see how RBAC validation plays out

**Comment by leahnp** [comment]
fixed by: https://github.com/samsung-cnct/k2-logging-fluentd-daemonset/pull/7
